---
Parameters:
  ENV:
    Description: 'Environment - dev/tst/acc/prd Default: tst'
    AllowedValues:
      - dev
      - tst
      - acc
      - prd
    Default: dev
    Type: String  

  # AppMeshMeshName:
  #   Type: String
  #   Description: Name of mesh

  # ECSServicesDomain:
  #   Type: String
  #   Description: DNS namespace used by services e.g. default.svc.cluster.local

  ColorTellerGreenTaskDefinition:
    Type: String
    Description: Task definition for ColorTeller Green Service
    Default: DEMO-colorteller-green

Resources:

  ### colorteller-green.default.svc.cluster.local
  ColorTellerGreenServiceDiscoveryRecord:
    Type: 'AWS::ServiceDiscovery::Service'
    Properties:
      Name: demo-colorteller-green
      DnsConfig:
        NamespaceId: 
          'Fn::ImportValue': demo-cluster-ECSServiceDiscoveryNamespace
        DnsRecords:
          - Type: A
            TTL: 300
      HealthCheckCustomConfig:
        FailureThreshold: 1

  ColorTellerGreenService:
    Type: AWS::ECS::Service
    Properties:
      Cluster: demo-dev
      DeploymentConfiguration:
        MaximumPercent: 200
        MinimumHealthyPercent: 100
      DesiredCount: 1
      LaunchType: FARGATE
      ServiceRegistries:
        - RegistryArn:
            'Fn::GetAtt': ColorTellerGreenServiceDiscoveryRecord.Arn
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          SecurityGroups:
            - 'Fn::ImportValue': demo-edge-network-securitygroup
          Subnets: 
            - 'Fn::ImportValue': demo-edge-network-subnet-1a
            - 'Fn::ImportValue': demo-edge-network-subnet-1b
            - 'Fn::ImportValue': demo-edge-network-subnet-1c
      TaskDefinition: { Ref: ColorTellerGreenTaskDefinition }
