Description: Creates ECS Cluster

Parameters:
  ENV:
    Description: Environment
    Default: dev
    Type: String  

Resources:
  # Fargate Cluster
  Cluster:
    Type: AWS::ECS::Cluster
    Properties: 
      ClusterName: !Sub "terra10-${ENV}" 

  ECSServiceDiscoveryNamespace:
    Type: AWS::ServiceDiscovery::PrivateDnsNamespace
    Properties:
      Vpc: vpc-f5c0c793
      Name: terra10.local

Outputs:
  ECSServiceDiscoveryNamespace:
    Description: A local namespace that will be used by all services in this cluster
    Value: !Ref ECSServiceDiscoveryNamespace
    Export:
      Name: !Sub '${AWS::StackName}-ECSServiceDiscoveryNamespace'